import pandas as pd
df = pd.read_csv('data/traffic/traffic_observations.csv')
print('CSV path: data/traffic/traffic_observations.csv')
print(f'CSV size: {df.memory_usage(deep=True).sum() / 1024:.1f} KB')
print(f'Row count: {len(df)}')
print(f'Columns: {list(df.columns)}')
print(f'Timestamp range: {df["observed_at"].min()} to {df["observed_at"].max()}')
print(f'Unique link_ids: {df["link_id"].nunique()}')
obs_per_link = df.groupby("link_id").size()
print(f'Obs per link: min={obs_per_link.min()}, max={obs_per_link.max()}, mean={obs_per_link.mean():.1f}')