import sys
sys.path.insert(0, r'C:\projects\UrbanOS')

# Read the current file
with open(r'C:\projects\UrbanOS\frontend\src\services\api\index.ts', 'rb') as f:
    content = f.read()

# Find the marker
idx = content.find(b'// Types for overview')
if idx >= 0:
    prefix = content[:idx]
    
    # New types as bytes
    new_types = b''
    new_types += b'// Types for overview\n'
    new_types += b'export interface ModuleKPI {\n'
    new_types += b'  label: string;\n'
    new_types += b'  value: any;\n'
    new_types += b'  unit: string;\n'
    new_types += b'}\n\n'
    new_types += b'export interface ModuleSummary {\n'
    new_types += b'  id: string;\n'
    new_types += b'  name: string;\n'
    new_types += b'  status: "normal" | "elevated" | "critical" | "unavailable";\n'
    new_types += b'  kpi: ModuleKPI | null;\n'
    new_types += b'  updated_at: string | null;\n'
    new_types += b'  detail_route: string;\n'
    new_types += b'}\n\n'
    new_types += b'export interface AlertItem {\n'
    new_types += b'  domain: string;\n'
    new_types += b'  severity: string;\n'
    new_types += b'  title: string;\n'
    new_types += b'  description: string;\n'
    new_types += b'  timestamp: string;\n'
    new_types += b'  affected_zones: string[];\n'
    new_types += b'}\n\n'
    new_types += b'export interface OverviewCityResponse {\n'
    new_types += b'  generated_at: string;\n'
    new_types += b'  modules: ModuleSummary[];\n'
    new_types += b'  alerts: AlertItem[];\n'
    new_types += b'  ai_brief: string | null;\n'
    new_types += b'}\n\n'
    new_types += b'export interface ModuleDetailResponse {\n'
    new_types += b'  module_id: string;\n'
    new_types += b'  module_name: string;\n'
    new_types += b'  status: string;\n'
    new_types += b'  kpi: ModuleKPI | null;\n'
    new_types += b'  updated_at: string | null;\n'
    new_types += b'  summary: string;\n'
    new_types += b'  alerts: AlertItem[];\n'
    new_types += b'  cross_domain: string[];\n'
    new_types += b'  detail_route: string;\n'
    new_types += b'}\n\n'
    new_types += b'export interface ChatRequest {\n'
    new_types += b'  message: string;\n'
    new_types += b'  module_id?: string;\n'
    new_types += b'}\n\n'
    new_types += b'export interface ChatResponse {\n'
    new_types += b'  response: string;\n'
    new_types += b'}\n\n'
    new_types += b'// Overview API functions\n'
    new_types += b'export async function fetchOverviewCity(): Promise<OverviewCityResponse> {\n'
    new_types += b'  const response = await fetch(API_BASE + "/api/overview/city", { cache: "no-store" });\n'
    new_types += b'  if (!response.ok) {\n'
    new_types += b'    throw new Error("Failed to fetch overview city: " + response.statusText);\n'
    new_types += b'  }\n'
    new_types += b'  return response.json();\n'
    new_types += b'}\n\n'
    new_types += b'export async function fetchOverviewModule(moduleId: string): Promise<ModuleDetailResponse> {\n'
    new_types += b'  const response = await fetch(API_BASE + "/api/overview/module/" + moduleId, { cache: "no-store" });\n'
    new_types += b'  if (!response.ok) {\n'
    new_types += b'    throw new Error("Failed to fetch overview module " + moduleId + ": " + response.statusText);\n'
    new_types += b'  }\n'
    new_types += b'  return response.json();\n'
    new_types += b'}\n\n'
    new_types += b'export async function fetchChat(message: string, moduleId?: string): Promise<ChatResponse> {\n'
    new_types += b'  const controller = new AbortController();\n'
    new_types += b'  const timeoutId = setTimeout(() => controller.abort(), 30000);\n'
    new_types += b'  const url = new URL(API_BASE + "/api/overview/chat");\n'
    new_types += b'  try {\n'
    new_types += b'    const response = await fetch(url.toString(), {\n'
    new_types += b'      method: "POST",\n'
    new_types += b'      headers: { "Content-Type": "application/json" },\n'
    new_types += b'      body: JSON.stringify({ message, module_id: moduleId }),\n'
    new_types += b'      cache: "no-store",\n'
    new_types += b'      signal: controller.signal,\n'
    new_types += b'    });\n'
    new_types += b'    if (!response.ok) {\n'
    new_types += b'      let detail = response.statusText;\n'
    new_types += b'      try { const errJson = await response.json(); if (errJson?.detail) detail = errJson.detail; } catch {}\n'
    new_types += b'      throw new Error("Failed to fetch chat response: " + detail);\n'
    new_types += b'    }\n'
    new_types += b'    return response.json();\n'
    new_types += b'  } catch (err) {\n'
    new_types += b'    if (err instanceof DOMException && err.name == "AbortError") {\n'
    new_types += b'      throw new Error("Chat request timed out");\n'
    new_types += b'    }\n'
    new_types += b'    throw err;\n'
    new_types += b'  } finally { clearTimeout(timeoutId); }\n'
    new_types += b'}\n'
    
    new_content = prefix + new_types
    with open(r'C:\projects\UrbanOS\frontend\src\services\api\index.ts', 'wb') as f:
        f.write(new_content)
    print('Updated successfully')
else:
    print('Could not find marker')